<a href="https://colab.research.google.com/github/alangilsanchez/MineriaDeDatos/blob/main/mineria_de_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Minería de Datos

##Primer parcial

### Introducción

#### Conceptos

**Minería de datos**: Data Mining es el proceso técnico y automático de explorar grandes conjuntos de datos para encontrar patrones, anomalías o correlaciones que no son evidentes a simple vista.

Su objetivo principal es transformar datos brutos en información valiosa que permita predecir comportamientos o tomar decisiones estratégicas fundamentadas.


**Ciencia de datos**: Es un campo interdisciplinario que combina matemáticas, estadística, programación avanzada e inteligencia artificial para extraer conocimientos de grandes volúmenes de datos.

A diferencia de la minería de datos (que se enfoca en encontrar patrones específicos), la ciencia de datos abarca todo el ciclo de vida del dato: desde su recolección y limpieza hasta la creación de modelos predictivos que responden a preguntas complejas de negocio.

#### Ciencia de Datos

#####Python Magic Commands

In [ ]:
#El comando magico %timeit sirve para evaluar el desempeño, en terminos de tiempo
# Sirve para una sola linea
%timeit L = [n ** 2 for n in range(1000)]

66.5 µs ± 939 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# El comando %%timeit sirve tambien para evaluar el desempeño
# solo que este abarca varias lineas de codigo en lugar una sola linea
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

75.1 µs ± 2.06 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit?

In [ ]:
%%timeit?

##### IPython and Shell Commands

In [ ]:
#Nos dice el listado de archivos en el directorio
!ls

sample_data


In [ ]:
#Nos cambia de directorio
%cd sample_data

/content/sample_data


In [ ]:
!ls

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [ ]:
#Visualiza archivo
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [ ]:
#It shows the envioroment variables
%env

SHELL=/bin/bash
COLAB_JUPYTER_TRANSPORT=ipc
CGROUP_MEMORY_EVENTS=/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events
VM_GCE_METADATA_HOST=169.254.169.253
HOSTNAME=90376a4d6483
MODEL_PROXY_HOST=https://mp.kaggle.net
LANGUAGE=en_US
TBE_RUNTIME_ADDR=172.28.0.1:8011
GCE_METADATA_TIMEOUT=3
COLAB_JUPYTER_IP=172.28.0.12
COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL=http://172.28.0.1:8013/
KMP_LISTEN_PORT=6000
TF_FORCE_GPU_ALLOW_GROWTH=true
ENV=/root/.bashrc
PWD=/content/sample_data
COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT=30s
TBE_EPHEM_CREDS_ADDR=172.28.0.1:8009
TBE_CREDS_ADDR=172.28.0.1:8008
JPY_SESSION_NAME=https://github.com/alangilsanchez/MineriaDeDatos/blob/main/Mineria_de_Datos.ipynb
COLAB_JUPYTER_TOKEN=
LAST_FORCED_REBUILD=20250623
TCLLIBPATH=/usr/share/tcltk/tcllib1.20
COLAB_KERNEL_MANAGER_PROXY_HOST=172.28.0.12
UV_BUILD_CONSTRAINT=
USE_AUTH_EPHEM=1
COLAB_WARMUP_DEFAULTS=1
HOME=/root
LANG=en_US.UTF-8
CLOUDSDK_CONFIG=/content/.config
UV_SYSTEM_PYTHON=true
COLAB_RELE

#####Understanding Data Types in Python

In [ ]:
#numpy fue creada en C ya que es mas rapido procesar datos que en Python
import numpy as np

In [ ]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
#Los convierte todos los datos en el mismo tipo (flotante) ya que numpy tiene fuerte tipado
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
#Podemos hacer listas de contencion pra hacer listas bidimensionales, con ciclos anidados
#Punto inicial i, punto final i+3 sin contemplarlo
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])