<a href="https://colab.research.google.com/github/alangilsanchez/MineriaDeDatos/blob/main/Mineria_De_Datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Minería de Datos

##Primer parcial

### Introducción

#### Conceptos

**Minería de datos**: Data Mining es el proceso técnico y automático de explorar grandes conjuntos de datos para encontrar patrones, anomalías o correlaciones que no son evidentes a simple vista.

Su objetivo principal es transformar datos brutos en información valiosa que permita predecir comportamientos o tomar decisiones estratégicas fundamentadas.


**Ciencia de datos**: Es un campo interdisciplinario que combina matemáticas, estadística, programación avanzada e inteligencia artificial para extraer conocimientos de grandes volúmenes de datos.

A diferencia de la minería de datos (que se enfoca en encontrar patrones específicos), la ciencia de datos abarca todo el ciclo de vida del dato: desde su recolección y limpieza hasta la creación de modelos predictivos que responden a preguntas complejas de negocio.

#### Ciencia de Datos

#####Python Magic Commands

In [ ]:
#El comando magico %timeit sirve para evaluar el desempeño, en terminos de tiempo
# Sirve para una sola linea
%timeit L = [n ** 2 for n in range(1000)]

66.5 µs ± 939 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
# El comando %%timeit sirve tambien para evaluar el desempeño
# solo que este abarca varias lineas de codigo en lugar una sola linea
%%timeit
L = []
for n in range(1000):
  L.append(n ** 2)

75.1 µs ± 2.06 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [ ]:
%timeit?

In [ ]:
%%timeit?

##### IPython and Shell Commands

In [ ]:
#Nos dice el listado de archivos en el directorio
!ls

sample_data


In [ ]:
#Nos cambia de directorio
%cd sample_data

/content/sample_data


In [ ]:
!ls

anscombe.json		      mnist_test.csv
california_housing_test.csv   mnist_train_small.csv
california_housing_train.csv  README.md


In [ ]:
#Visualiza archivo
!cat README.md

This directory includes a few sample datasets to get you started.

*   `california_housing_data*.csv` is California housing data from the 1990 US
    Census; more information is available at:
    https://docs.google.com/document/d/e/2PACX-1vRhYtsvc5eOR2FWNCwaBiKL6suIOrxJig8LcSBbmCbyYsayia_DvPOOBlXZ4CAlQ5nlDD8kTaIDRwrN/pub

*   `mnist_*.csv` is a small sample of the
    [MNIST database](https://en.wikipedia.org/wiki/MNIST_database), which is
    described at: http://yann.lecun.com/exdb/mnist/

*   `anscombe.json` contains a copy of
    [Anscombe's quartet](https://en.wikipedia.org/wiki/Anscombe%27s_quartet); it
    was originally described in

    Anscombe, F. J. (1973). 'Graphs in Statistical Analysis'. American
    Statistician. 27 (1): 17-21. JSTOR 2682899.

    and our copy was prepared by the
    [vega_datasets library](https://github.com/altair-viz/vega_datasets/blob/4f67bdaad10f45e3549984e17e1b3088c731503d/vega_datasets/_data/anscombe.json).


In [ ]:
#It shows the envioroment variables
%env

SHELL=/bin/bash
COLAB_JUPYTER_TRANSPORT=ipc
CGROUP_MEMORY_EVENTS=/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events
VM_GCE_METADATA_HOST=169.254.169.253
HOSTNAME=90376a4d6483
MODEL_PROXY_HOST=https://mp.kaggle.net
LANGUAGE=en_US
TBE_RUNTIME_ADDR=172.28.0.1:8011
GCE_METADATA_TIMEOUT=3
COLAB_JUPYTER_IP=172.28.0.12
COLAB_LANGUAGE_SERVER_PROXY_ROOT_URL=http://172.28.0.1:8013/
KMP_LISTEN_PORT=6000
TF_FORCE_GPU_ALLOW_GROWTH=true
ENV=/root/.bashrc
PWD=/content/sample_data
COLAB_LANGUAGE_SERVER_PROXY_REQUEST_TIMEOUT=30s
TBE_EPHEM_CREDS_ADDR=172.28.0.1:8009
TBE_CREDS_ADDR=172.28.0.1:8008
JPY_SESSION_NAME=https://github.com/alangilsanchez/MineriaDeDatos/blob/main/Mineria_de_Datos.ipynb
COLAB_JUPYTER_TOKEN=
LAST_FORCED_REBUILD=20250623
TCLLIBPATH=/usr/share/tcltk/tcllib1.20
COLAB_KERNEL_MANAGER_PROXY_HOST=172.28.0.12
UV_BUILD_CONSTRAINT=
USE_AUTH_EPHEM=1
COLAB_WARMUP_DEFAULTS=1
HOME=/root
LANG=en_US.UTF-8
CLOUDSDK_CONFIG=/content/.config
UV_SYSTEM_PYTHON=true
COLAB_RELE

#####Understanding Data Types in Python

In [ ]:
#numpy fue creada en C ya que es mas rapido procesar datos que en Python
import numpy as np

In [ ]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [ ]:
#Los convierte todos los datos en el mismo tipo (flotante) ya que numpy tiene fuerte tipado
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [ ]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
np.array([1, 2, 3, 4], dtype='int')

array([1, 2, 3, 4])

In [ ]:
#Podemos hacer listas de contencion pra hacer listas bidimensionales, con ciclos anidados
#Punto inicial i, punto final i+3 sin contemplarlo
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

#####NumPy Array Attributes

In [ ]:
import numpy as np
np.random.seed(0)  # seed for reproducibility
                      #numeros aleatorios entre 0 y 10 (Sin considerar 1ñ 10, python no considera el limite superior)
x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array ,3 renglones 4 columnas
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

In [ ]:
print("x3 ndim: ", x3.ndim) #La propiedad ndim nos dice el numero de dimensiones
print("x3 shape:", x3.shape) #
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


In [ ]:
print(x2.dtype) # Dtype nos dice el tipo de dato, entero de 64 bits en 8 bloque de bytes

int64


In [ ]:
#itemsize nos regresa el tamaño en site
print("itemsize:", x3.itemsize, "bytes")
print("nbytes:", x3.nbytes, "bytes") #nbytes es el tamaño de cada elemento por el tamaño

itemsize: 8 bytes
nbytes: 480 bytes


#####Array Indexing: Accessing Single Elements

In [ ]:
x1 #Son los digitos en 0 y 10 creados con el random

array([5, 0, 3, 3, 7, 9])

In [ ]:
x1[0] #Colocamos el indice del elemento a extraer, en este caso el primer elemento tiene el indice 0

np.int64(5)

In [ ]:
x1[4]

np.int64(7)

In [ ]:
x1[-1] #Nos regresa el ultimo elemento del ndarray

np.int64(9)

In [ ]:
x2 #Arreglo bidimensional

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [ ]:
x2[0,0]

np.int64(3)

In [ ]:
x2[0,2]

np.int64(2)

In [ ]:
#Tambien se puede contar desde atras
x2[2, -1]

np.int64(7)

In [ ]:
x2[0, 0] = 12 # Asignar un nuevo valor (12) al renglon 0

###Estadistica Basica


####Medidas Estadísticas Básicas

In [ ]:
data = np.array([1, 2, 3, 4, 5])
media = np.mean(data)
print(media)

3.0


####Promedio (Average) y Promedio Ponderado

In [ ]:
data = np.array([1, 2, 3, 4, 5])
weights = np.array([1, 2, 3, 4, 5])
promedio = np.average(data)
promedio_ponderado = np.average(data, weights=weights)

In [ ]:
print(promedio)
print(promedio_ponderado)

3.0
3.6666666666666665


####Mediana

In [ ]:
mediana = np.median(data)

####Varianza y Desviación Estándar

In [ ]:
varianza = np.var(data)
desviacion = np.std(data) #std = standar
# Desviacion raiz cuadrarda de la varianza

####Generación de Datos Aleatorios

In [ ]:
muestra = np.random.normal(0, 1, 1000) #media 0, desviacion estandar 1, genera 1000 datos
print(np.mean(muestra), np.std(muestra))

-0.006543456960417206 1.0059985778093545


####Correlación

In [ ]:
corr = np.corrcoef([1,2,3], [1,5,7])
corr

array([[1.        , 0.98198051],
       [0.98198051, 1.        ]])

#### Funciones Estadísticas Adicionales (NumPy)

Cuantiles (np.quantile)

Percentiles (np.percentile)

Histogramas (np.histogram)

Covarianza (np.cov)

Manejo de NaN (np.nanmean, etc.)